name: movemedical_model
description: Move Medical Model

version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:

  http: ^0.12.0+1
  logging: ^0.11.3+2
  intl: ^0.15.7
  web_socket_channel: ^1.0.9

  modux:
    path: ../modux-dart
#    git: git://github.com/movemedical/modux-dart

  movemedical_api:
    path: ../move-dart-api
#    git: git://github.com/movemedical/move-dart-api

dev_dependencies:
  analyzer: ^0.35.4
  build: ^1.1.3
  build_runner: ^1.3.1
  test: ^1.6.2
  mockito: ^4.0.0

  built_value_generator:
#    path: ../built-value-generator
    git: https://github.com/movemedical/built-value-generator

  modux_generator:
    path: ../modux-dart-generator
#    git: git://github.com/movemedical/modux-dart-generator
