name: movemedical_model
description: Move Medical Model

version: 1.0.0+1

environment:
  sdk: ">=2.1.0-dev.9.4 <3.0.0"

dependencies:

  http: ^0.12.0+1
  logging: ^0.11.3+2
  intl: ^0.15.7
  web_socket_channel: ^1.0.9
  built_value: ^6.3.1

  modux:
    path: ../modux-dart
#    git: git://github.com/movemedical/modux-dart

  movemedical_api:
    path: ../move-dart-api
#    git: git://github.com/movemedical/move-dart-api

dev_dependencies:
  analyzer: ^0.34.3
  build: ^1.0.3
  build_runner: ^1.1.3

  source_gen: ^0.9.4+1
  test: ^1.5.1
  mockito: ^4.0.0

  built_value_generator:
    git: https://github.com/movemedical/built-value-generator

  modux_generator:
    git: git://github.com/movemedical/modux-dart-generator
